# Generated by Django 5.2 on 2025-04-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0002_alter_message_thread_flashcards_quizzes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcards',
            old_name='answer',
            new_name='title',
        ),
    ]
