# Generated by Django 5.2.5 on 2025-09-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0004_quizzes_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
