# Generated by Django 5.2.5 on 2025-09-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0005_message_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.TextField(default=''),
        ),
    ]
