# Generated by Django 5.2 on 2025-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0003_rename_answer_flashcards_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='choices',
            field=models.TextField(default='{}'),
        ),
    ]
