# Generated by Django 5.2.5 on 2026-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0007_alter_thread_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.TextField(default='')),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
