# Generated by Django 5.2.5 on 2026-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0008_aispace'),
    ]

    operations = [
        migrations.AddField(
            model_name='aispace',
            name='aiSpace',
            field=models.TextField(default='Ollama'),
        ),
    ]
