# Generated by Django 5.2.5 on 2026-05-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0009_aispace_aispace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aispace',
            name='aiSpace',
        ),
    ]
