# Generated by Django 5.2.6 on 2026-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0010_remove_aispace_aispace'),
    ]

    operations = [
        migrations.AddField(
            model_name='aispace',
            name='base_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aispace',
            name='model_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
