# Generated by Django 5.2.6 on 2026-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIBuddy', '0011_aispace_base_url_aispace_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aispace',
            name='ai_space',
            field=models.TextField(default='Ollama'),
        ),
    ]
